export const industries =[
    "Agriculture",
    "Automotive",
    "Aerospace",
    "Banking",
    "Biotechnology",
    "Chemical",
    "Construction",
    "Consumer Goods",
    "Defense",
    "Education",
    "Energy",
    "Entertainment",
    "Environmental Services",
    "Fashion",
    "Financial Services",
    "Food & Beverage",
    "Government",
    "Healthcare",
    "Hospitality",
    "Human Resources",
    "Information Technology",
    "Insurance",
    "Legal Services",
    "Logistics",
    "Manufacturing",
    "Marine",
    "Marketing",
    "Media & Broadcasting",
    "Mining",
    "Non-Profit",
    "Oil & Gas",
    "Pharmaceuticals",
    "Public Relations",
    "Real Estate",
    "Retail",
    "Software",
    "Telecommunications",
    "Textile",
    "Tourism",
    "Transportation",
    "Utilities",
    "Venture Capital",
    "Waste Management",
    "Wholesale",
    "Agribusiness",
    "Apparel",
    "Architecture",
    "Art & Design",
    "Aviation",
    "Beauty & Cosmetics",
    "Book Publishing",
    "Call Centers",
    "Cybersecurity",
    "Data Analytics",
    "E-commerce",
    "Engineering",
    "Event Planning",
    "Facilities Management",
    "Fitness",
    "Franchising",
    "Freight & Shipping",
    "Furniture",
    "Gaming",
    "Graphic Design",
    "Green Technology",
    "Hardware",
    "Home Improvement",
    "Interior Design",
    "Jewelry",
    "Language Services",
    "Law Enforcement",
    "Libraries",
    "Luxury Goods",
    "Market Research",
    "Mechanical",
    "Metals & Mining",
    "Mobile Apps",
    "Museums",
    "Music",
    "Nanotechnology",
    "Non-Alcoholic Beverages",
    "Office Supplies",
    "Outsourcing",
    "Packaging",
    "Paper & Forest Products",
    "Petroleum",
    "Philanthropy",
    "Photography",
    "Plastic & Rubber Products",
    "Printing",
    "Professional Services",
    "Public Safety",
    "Publishing",
    "Recycling",
    "Renewable Energy",
    "Robotics",
    "Security",
    "Semiconductors",
    "Social Media",
    "Space Exploration",
    "Sports",
    "Supply Chain",
    "Sustainable Development",
    "Television",
    "Textiles",
    "Translation Services",
    "Travel",
    "Video Production",
    "Warehousing",
    "Web Development",
    "Wine & Spirits",
    "Wood Products",
    "Writing & Editing"
]


export const legalStructures = [
    "Sole Proprietorship",
    "Partnership",
    "Limited Liability Company (LLC)",
    "Corporation (C Corp)",
    "S Corporation (S Corp)",
    "Nonprofit Organization",
    "Cooperative",
    "Limited Partnership (LP)",
    "Limited Liability Partnership (LLP)",
    "Professional Corporation (PC)",
    "Benefit Corporation (B Corp)",
    "Joint Venture"
  ];
export const regions = [
    // Continents
    "Africa",
    "Antarctica",
    "Asia",
    "Europe",
    "North America",
    "Oceania",
    "South America",
  
    // Subregions of Africa
    "Northern Africa",
    "Sub-Saharan Africa",
    "Eastern Africa",
    "Middle Africa",
    "Southern Africa",
    "Western Africa",
    "Horn of Africa",
  
    // Subregions of Asia
    "Central Asia",
    "East Asia",
    "South Asia",
    "Southeast Asia",
    "Western Asia",
    "North Asia",
    "Caucasus",
    "Middle East",
  
    // Subregions of Europe
    "Eastern Europe",
    "Northern Europe",
    "Southern Europe",
    "Western Europe",
    "Central Europe",
    "Baltic States",
    "Balkans",
    "Scandinavia",
    "Iberian Peninsula",
    "British Isles",
  
    // Subregions of North America
    "Caribbean",
    "Central America",
    "Northern America",
    "Great Plains",
    "Rocky Mountains",
    "Pacific Northwest",
    "Midwest",
    "New England",
    "Southeastern United States",
  
    // Subregions of South America
    "Andean States",
    "Southern Cone",
    "Amazon Basin",
    "Gran Chaco",
    "Patagonia",
  
    // Subregions of Oceania
    "Australia",
    "Melanesia",
    "Micronesia",
    "Polynesia",
    "New Zealand",
    "Papua New Guinea",
    "Hawaii",
  
    // Arctic and Antarctic Regions
    "Arctic",
    "Subantarctic Islands",
  
    // Additional Regional Classifications
    "Arabian Peninsula",
    "Indian Subcontinent",
    "Maghreb",
    "Sahel",
    "Siberia",
    "Tropics",
    "Mediterranean Basin",
    "Black Sea Region",
    "Gulf States",
    "Indochina",
    "Levant",
    "Western Balkans",
    "Eastern Mediterranean",
    "Central Asia",
    "Far East",
    "Saharan Desert",
    "South Pacific"
  ];


export const skillsAndExpertise = [
    {
      type: "Leadership",
      values: [
        "Visionary Leadership",
        "Team Building",
        "Strategic Planning",
        "Decision Making",
        "Conflict Resolution",
        "Motivation",
        "Crisis Management",
        "Delegation",
        "Emotional Intelligence",
        "Mentorship",
        "Inspirational Leadership",
        "Change Management",
        "Ethical Leadership",
        "Public Speaking",
        "Cultural Sensitivity"
      ]
    },
    {
      type: "Technical Skills",
      values: [
        "Full Stack Development",
        "Backend Development",
        "Frontend Development",
        "DevOps",
        "Cloud Computing",
        "Data Science",
        "Machine Learning",
        "Artificial Intelligence",
        "Cybersecurity",
        "Blockchain Technology",
        "Mobile Development",
        "Web Development",
        "Database Management",
        "API Integration",
        "Software Architecture",
        "Quality Assurance",
        "Agile Methodology",
        "Version Control (Git)",
        "Testing & Debugging",
        "Containerization (Docker)",
        "Microservices Architecture",
        "Network Administration",
        "System Design",
        "Automation",
        "UI/UX Design",
        "Human-Computer Interaction"
      ]
    },
    {
      type: "Financial Skills",
      values: [
        "Financial Modeling",
        "Budgeting",
        "Accounting",
        "Tax Planning",
        "Fundraising",
        "Venture Capital",
        "Investor Relations",
        "Cash Flow Management",
        "Cost Control",
        "Financial Reporting",
        "Valuation",
        "Equity Management",
        "Financial Forecasting",
        "Business Valuation",
        "Capital Allocation",
        "Revenue Modeling",
        "P&L Management",
        "Investment Strategy",
        "Financial Analysis",
        "Risk Management",
        "Debt Financing",
        "Profit Maximization",
        "Cost-Benefit Analysis"
      ]
    },
    {
      type: "Marketing & Sales",
      values: [
        "Brand Development",
        "Market Research",
        "Product Positioning",
        "Pricing Strategy",
        "Customer Segmentation",
        "Digital Marketing",
        "Content Marketing",
        "SEO/SEM",
        "Social Media Marketing",
        "Email Marketing",
        "Sales Strategy",
        "Lead Generation",
        "Conversion Rate Optimization",
        "Customer Acquisition",
        "Sales Funnel Management",
        "Public Relations",
        "Partnership Development",
        "Customer Relationship Management (CRM)",
        "Influencer Marketing",
        "Copywriting",
        "Advertising",
        "Customer Retention",
        "Affiliate Marketing",
        "Event Marketing",
        "Brand Storytelling",
        "Sales Pitch Development",
        "Product Marketing",
        "Demand Generation"
      ]
    },
    {
      type: "Operational Expertise",
      values: [
        "Supply Chain Management",
        "Logistics",
        "Inventory Management",
        "Operations Strategy",
        "Process Optimization",
        "Lean Manufacturing",
        "Six Sigma",
        "Quality Control",
        "Vendor Management",
        "Project Management",
        "Resource Allocation",
        "SOP Development",
        "Outsourcing",
        "Procurement",
        "Production Planning",
        "Workforce Planning",
        "KPI Development",
        "Performance Metrics",
        "Continuous Improvement",
        "Capacity Planning",
        "Operational Risk Management",
        "Facility Management",
        "Business Process Reengineering"
      ]
    },
    {
      type: "Legal & Compliance",
      values: [
        "Contract Negotiation",
        "Corporate Governance",
        "Intellectual Property",
        "Employment Law",
        "Regulatory Compliance",
        "Data Privacy",
        "Trademark Law",
        "Patent Law",
        "Mergers & Acquisitions",
        "Business Licensing",
        "Legal Risk Management",
        "Compliance Auditing",
        "Corporate Law",
        "Environmental Compliance",
        "Ethics & Compliance",
        "Litigation Management",
        "Insurance",
        "Due Diligence",
        "Cyber Law",
        "Consumer Protection Laws",
        "Non-Disclosure Agreements (NDA)",
        "Terms of Service",
        "Privacy Policy",
        "Anti-Money Laundering (AML)"
      ]
    },
    {
      type: "Human Resources",
      values: [
        "Talent Acquisition",
        "Employee Engagement",
        "Performance Management",
        "Compensation & Benefits",
        "HR Strategy",
        "Diversity & Inclusion",
        "Learning & Development",
        "Succession Planning",
        "Employee Relations",
        "HR Analytics",
        "Workforce Planning",
        "Onboarding",
        "Employee Retention",
        "HR Compliance",
        "Organizational Development",
        "Leadership Development",
        "Conflict Resolution",
        "Payroll Management",
        "HR Technology",
        "Labor Relations",
        "Employee Wellness Programs",
        "Job Analysis",
        "Workforce Diversity",
        "Employee Satisfaction",
        "HR Policy Development",
        "Recruitment Marketing"
      ]
    },
    {
      type: "Product Management",
      values: [
        "Product Lifecycle Management",
        "Product Strategy",
        "Roadmap Development",
        "User Experience (UX)",
        "User Research",
        "Product Design",
        "Agile Product Development",
        "Feature Prioritization",
        "MVP Development",
        "Product Launch",
        "Competitive Analysis",
        "Market Fit Analysis",
        "Product Analytics",
        "A/B Testing",
        "User Feedback Management",
        "Product Vision",
        "Cross-functional Collaboration",
        "Backlog Management",
        "Prototyping",
        "Customer Development",
        "Product Roadmapping",
        "Product Scaling",
        "User Persona Development",
        "Value Proposition Design"
      ]
    },
    {
      type: "Strategy & Innovation",
      values: [
        "Business Strategy",
        "Growth Strategy",
        "Market Entry Strategy",
        "Competitive Strategy",
        "Innovation Management",
        "Disruptive Innovation",
        "Corporate Strategy",
        "Business Model Innovation",
        "Scenario Planning",
        "SWOT Analysis",
        "Blue Ocean Strategy",
        "Strategic Partnerships",
        "Industry Analysis",
        "Strategic Thinking",
        "Go-to-Market Strategy",
        "Technology Roadmapping",
        "Sustainability Strategy",
        "Open Innovation",
        "Ecosystem Development",
        "Market Expansion",
        "Strategic Alliances",
        "Corporate Venturing",
        "Innovation Ecosystems",
        "Foresight Analysis",
        "Corporate Social Responsibility (CSR)"
      ]
    },
    {
      type: "Communication",
      values: [
        "Effective Communication",
        "Public Speaking",
        "Negotiation",
        "Active Listening",
        "Interpersonal Skills",
        "Presentation Skills",
        "Nonverbal Communication",
        "Written Communication",
        "Conflict Resolution",
        "Cross-cultural Communication",
        "Internal Communication",
        "Stakeholder Communication",
        "Media Relations",
        "Crisis Communication",
        "Brand Messaging",
        "Customer Communication",
        "Employee Communication",
        "Influence & Persuasion",
        "Networking",
        "Storytelling",
        "Feedback Delivery",
        "Community Engagement",
        "Investor Communication",
        "Press Releases",
        "Corporate Communication"
      ]
    },
    {
      type: "Technology & Innovation",
      values: [
        "Artificial Intelligence",
        "Machine Learning",
        "Blockchain",
        "Augmented Reality",
        "Virtual Reality",
        "Quantum Computing",
        "IoT (Internet of Things)",
        "5G Technology",
        "Biotechnology",
        "Nanotechnology",
        "Clean Technology",
        "SaaS (Software as a Service)",
        "PaaS (Platform as a Service)",
        "Cloud Computing",
        "Big Data",
        "Data Analytics",
        "Data Warehousing",
        "Cybersecurity",
        "Automation",
        "Edge Computing",
        "DevOps",
        "Digital Transformation",
        "IT Infrastructure",
        "Software Development",
        "Mobile Technology",
        "Tech Stack Optimization",
        "Technical Debt Management",
        "IT Governance",
        "Technology Risk Management"
      ]
    },
    {
      type: "Customer Experience",
      values: [
        "Customer Journey Mapping",
        "User Experience (UX)",
        "Customer Relationship Management",
        "Customer Support",
        "Customer Feedback Management",
        "Net Promoter Score (NPS)",
        "Customer Retention Strategies",
        "Personalization",
        "Omni-channel Experience",
        "Customer Success Management",
        "Voice of Customer (VoC)",
        "Customer Advocacy",
        "Churn Analysis",
        "Customer Data Analysis",
        "Customer Loyalty Programs",
        "CX Strategy",
        "User Interface (UI) Design",
        "Customer Empathy",
        "Service Design",
        "Customer Touchpoint Management",
        "Experience Optimization",
        "Customer Onboarding",
        "CX Metrics",
        "CX Innovation",
        "CX Technology",
        "Customer Education"
      ]
    },
    {
      type: "Entrepreneurial Skills",
      values: [
        "Risk Management",
        "Opportunity Identification",
        "Resourcefulness",
        "Resilience",
        "Problem Solving",
        "Creativity",
        "Adaptability",
        "Decision Making",
        "Networking",
        "Lean Startup Methodology",
        "Bootstrapping",
        "Venture Building",
        "Pitch Development",
        "Fundraising",
        "Market Research",
        "Customer Discovery",
        "MVP Development",
        "Iterative Development",
        "Growth Hacking",
        "Time Management",
        "Business Planning",
        "Strategic Vision",
        "Competitive"]
    },
    {
        type: "Entrepreneurial Skills",
        values: [
          "Risk Management",
          "Opportunity Identification",
          "Resourcefulness",
          "Resilience",
          "Problem Solving",
          "Creativity",
          "Adaptability",
          "Decision Making",
          "Networking",
          "Lean Startup Methodology",
          "Bootstrapping",
          "Venture Building",
          "Pitch Development",
          "Fundraising",
          "Market Research",
          "Customer Discovery",
          "MVP Development",
          "Iterative Development",
          "Growth Hacking",
          "Time Management",
          "Business Planning",
          "Strategic Vision",
          "Competitive Analysis",
          "Scalability",
          "Innovation",
          "Revenue Generation",
          "Business Development",
          "Go-to-Market Strategy"
        ]
      },
      {
        type: "Networking & Relationship Management",
        values: [
          "Building Professional Networks",
          "Relationship Building",
          "Strategic Partnerships",
          "Stakeholder Engagement",
          "Industry Connections",
          "Client Relationship Management",
          "Negotiation Skills",
          "Influencing Skills",
          "Networking Events",
          "Collaborations",
          "Cross-functional Collaboration",
          "Public Relations",
          "Business Networking",
          "Mentorship",
          "Strategic Alliances",
          "Community Engagement",
          "Investor Relations",
          "Vendor Relations",
          "Government Relations",
          "Media Relations",
          "Affiliate Partnerships",
          "Investor Pitching",
          "Cross-industry Networking",
          "Business Ecosystems"
        ]
      },
      {
        type: "Project Management",
        values: [
          "Project Planning",
          "Task Management",
          "Resource Management",
          "Timeline Management",
          "Budget Management",
          "Risk Assessment",
          "Milestone Tracking",
          "Project Scope Management",
          "Stakeholder Communication",
          "Change Management",
          "Agile Project Management",
          "Waterfall Project Management",
          "Project Documentation",
          "Project Reporting",
          "Team Coordination",
          "Project Delivery",
          "Quality Assurance",
          "Project Evaluation",
          "Dependency Management",
          "Project Scheduling",
          "Project Initiation",
          "Project Execution",
          "Project Closure",
          "Risk Mitigation"
        ]
      },
      {
        type: "Sales & Business Development",
        values: [
          "Lead Generation",
          "Sales Strategy",
          "Client Acquisition",
          "Sales Forecasting",
          "Pipeline Management",
          "Account Management",
          "Sales Negotiation",
          "Sales Presentations",
          "Sales Analytics",
          "Market Analysis",
          "Client Retention",
          "Strategic Sales Planning",
          "Sales Training",
          "Sales Campaigns",
          "Business Development Strategy",
          "Partnership Development",
          "Deal Closure",
          "Customer Engagement",
          "Sales Enablement",
          "Revenue Growth",
          "Sales Metrics",
          "Sales Process Optimization",
          "Sales Reporting",
          "B2B Sales",
          "B2C Sales",
          "Lead Qualification"
        ]
      },
      {
        type: "Cultural & Global Awareness",
        values: [
          "Cross-cultural Communication",
          "Global Business Practices",
          "Cultural Sensitivity",
          "International Markets",
          "Global Trends",
          "Cultural Competence",
          "Multicultural Team Management",
          "Global Negotiation",
          "International Law",
          "Cultural Adaptation",
          "Global Economic Trends",
          "International Trade",
          "Regional Market Understanding",
          "Global Strategy",
          "Cultural Intelligence",
          "International Relations",
          "Global Supply Chain Management",
          "International Marketing",
          "Geopolitical Awareness",
          "Cross-border Collaboration",
          "International Business Etiquette",
          "Global Diversity",
          "Global Branding"
        ]
      },
      {
        type: "Innovation & Creativity",
        values: [
          "Creative Problem Solving",
          "Innovation Management",
          "Ideation Techniques",
          "Design Thinking",
          "Creative Strategy",
          "Product Innovation",
          "Innovation Ecosystems",
          "Creativity in Business",
          "Disruptive Innovation",
          "Prototype Development",
          "Innovation Workshops",
          "Creative Leadership",
          "Innovation Metrics",
          "Innovation Culture",
          "Creative Collaboration",
          "Futures Thinking",
          "Experimental Mindset",
          "Innovation Roadmapping",
          "Creativity Techniques",
          "Cross-disciplinary Innovation",
          "Innovation Trends",
          "Creative Process Management",
          "Innovation Strategy"
        ]
      },
      {
        type: "Technology Management",
        values: [
          "IT Strategy",
          "Technology Integration",
          "Digital Transformation",
          "Technology Roadmaps",
          "Technology Adoption",
          "Tech Stack Management",
          "IT Governance",
          "Technology Risk Management",
          "Emerging Technologies",
          "Infrastructure Management",
          "Technology Procurement",
          "Technology Portfolio Management",
          "Enterprise Architecture",
          "Technology Assessment",
          "IT Infrastructure Planning",
          "Technology Scalability",
          "Innovation Technology Management",
          "Cybersecurity Strategy",
          "Technology Budgeting",
          "IT Compliance",
          "Data Management",
          "Cloud Solutions Management",
          "Technology Optimization",
          "Tech Trends Analysis"
        ]
      }
]